
git:
  depth: 3

os:
  - linux
  - osx
  - windows

addons:

  apt:
    packages:
      - nodejs
      - npm
    update: true

  homebrew:
    packages:
    - node
    - npm
    update: true

language: node_js

install:
  - npm install